import { Injectable, signal } from '@angular/core';
import { Product, ProductCategory } from '../models/product.model';
import { Testimonial, TeamMember, Certification, Stat } from '../models/testimonial.model';
import { BlogPost } from '../models/blog.model';

@Injectable({ providedIn: 'root' })
export class DataService {

  getStats(): Stat[] {
    return [
      { value: 7, suffix: '+', label: 'Years of Excellence', icon: 'verified', description: 'A focused history of pioneering sustainable solutions' },
      { value: 500, suffix: '+', label: 'Products Delivered', icon: 'inventory_2', description: 'Serving diverse industries worldwide' },
      { value: 200, suffix: '+', label: 'Happy Clients', icon: 'groups', description: 'Trusted by leading brands globally' },
      { value: 30, suffix: '+', label: 'Countries Served', icon: 'public', description: 'Global presence with local expertise' },
    ];
  }

  getProducts(): Product[] {
    return [
      {
        id: 'bc-001',
        name: 'EcoPLA-X500',
        slug: 'ecopla-x500',
        category: 'biodegradable-compounds',
        description: 'High-performance PLA-based biodegradable compound with enhanced mechanical properties. Ideal for injection molding and extrusion applications where compostability is required.',
        shortDescription: 'Premium PLA-based biodegradable compound for injection molding and extrusion.',
        applications: ['Packaging', 'Disposable Cutlery', 'Food Containers', 'Agricultural Films'],
        features: ['100% Compostable', 'High Heat Resistance', 'Excellent Impact Strength', 'FDA Compliant'],
        specifications: [
          { label: 'MFI', value: '5-8', unit: 'g/10min' },
          { label: 'Tensile Strength', value: '50-55', unit: 'MPa' },
          { label: 'HDT', value: '55-60', unit: '°C' },
          { label: 'Biodegradation', value: '90', unit: 'days' },
        ],
        images: ['assets/images/products/biopla-x500.jpg'],
        thumbnail: 'assets/images/products/biopla-x500-thumb.jpg',
        badge: 'Bestseller',
        isFeatured: true,
        certifications: ['ISO 14001', 'EN 13432', 'ASTM D6400'],
        tags: ['PLA', 'Compostable', 'Packaging', 'FDA'],
      },
      {
        id: 'nfc-002',
        name: 'JuteComp-NF30',
        slug: 'jutecomp-nf30',
        category: 'natural-fiber-composites',
        description: 'Jute fiber reinforced PP composite offering exceptional strength-to-weight ratio. A sustainable alternative to glass fiber composites in automotive and construction applications.',
        shortDescription: '30% jute fiber reinforced PP composite for automotive and construction.',
        applications: ['Automotive Interior Panels', 'Construction Boards', 'Furniture', 'Consumer Goods'],
        features: ['30% Jute Fiber Content', 'Superior Stiffness', 'Lightweight', 'Reduced Carbon Footprint'],
        specifications: [
          { label: 'Fiber Content', value: '30', unit: '%' },
          { label: 'Tensile Modulus', value: '3500', unit: 'MPa' },
          { label: 'Flexural Strength', value: '65', unit: 'MPa' },
          { label: 'Density', value: '1.05', unit: 'g/cm³' },
        ],
        images: ['assets/images/products/jutecomp-nf30.jpg'],
        thumbnail: 'assets/images/products/jutecomp-nf30-thumb.jpg',
        badge: 'Popular',
        isFeatured: true,
        certifications: ['ISO 9001', 'RoHS'],
        tags: ['Jute', 'PP', 'Automotive', 'Natural Fiber'],
      },
      {
        id: 'bm-003',
        name: 'EcoColor MB-200',
        slug: 'ecocolor-mb200',
        category: 'compostable-masterbatches',
        description: 'Compostable color masterbatch compatible with PLA, PBAT, and other biodegradable polymers. Delivers vibrant, consistent colors while maintaining compostability compliance.',
        shortDescription: 'Compostable color masterbatch compatible with all biodegradable polymers.',
        applications: ['Compostable Packaging', 'Agricultural Films', 'Compostable Bags', 'Food Service Items'],
        features: ['Compostable Carrier', 'High Color Strength', 'Good Dispersion', 'Compostability Maintained'],
        specifications: [
          { label: 'Let-Down Ratio', value: '2-5', unit: '%' },
          { label: 'Moisture Content', value: '<0.2', unit: '%' },
          { label: 'Processing Temp', value: '160-200', unit: '°C' },
          { label: 'Shelf Life', value: '24', unit: 'months' },
        ],
        images: ['assets/images/products/ecocolor-mb200.jpg'],
        thumbnail: 'assets/images/products/ecocolor-mb200-thumb.jpg',
        isNew: true,
        isFeatured: true,
        certifications: ['EN 13432', 'OK Compost'],
        tags: ['Masterbatch', 'Color', 'Compostable', 'PLA'],
      },
      {
        id: 'sp-004',
        name: 'FlexBio PBAT-100',
        slug: 'flexbio-pbat100',
        category: 'specialty-polymers',
        description: 'Premium PBAT resin with excellent flexibility and biodegradability. Perfect for thin film applications requiring compostability and good elongation properties.',
        shortDescription: 'Premium PBAT resin for flexible films and compostable bags.',
        applications: ['Compostable Bags', 'Mulch Films', 'Wrap Films', 'Soft Touch Parts'],
        features: ['High Flexibility', 'Excellent Tear Resistance', 'Soil Biodegradable', 'Hot Sealable'],
        specifications: [
          { label: 'Elongation', value: '>500', unit: '%' },
          { label: 'Tensile Strength', value: '15-20', unit: 'MPa' },
          { label: 'MFI', value: '3-4', unit: 'g/10min' },
          { label: 'Biodegradation', value: '6', unit: 'months in soil' },
        ],
        images: ['assets/images/products/flexbio-pbat.jpg'],
        thumbnail: 'assets/images/products/flexbio-pbat-thumb.jpg',
        isFeatured: false,
        certifications: ['EN 13432', 'ASTM D6400', 'DIN CERTCO'],
        tags: ['PBAT', 'Film', 'Flexible', 'Biodegradable'],
      },
      {
        id: 'nfc-005',
        name: 'CelluForce CF-20',
        slug: 'celluforce-cf20',
        category: 'natural-fiber-composites',
        description: 'Cellulose fiber reinforced compound with exceptional surface finish and dimensional stability. Designed for consumer electronics and premium packaging applications.',
        shortDescription: 'Cellulose fiber composite for premium consumer applications.',
        applications: ['Consumer Electronics', 'Premium Packaging', 'Personal Care', 'Household Items'],
        features: ['Premium Surface Finish', 'Dimensional Stability', 'Recyclable', 'Low Emission'],
        specifications: [
          { label: 'Fiber Content', value: '20', unit: '%' },
          { label: 'Surface Gloss', value: '85+', unit: 'GU' },
          { label: 'Shrinkage', value: '0.4-0.6', unit: '%' },
          { label: 'TVOC', value: '<50', unit: 'μg/m³' },
        ],
        images: ['assets/images/products/celluforce-cf20.jpg'],
        thumbnail: 'assets/images/products/celluforce-cf20-thumb.jpg',
        isNew: true,
        certifications: ['REACH', 'RoHS', 'ISO 9001'],
        tags: ['Cellulose', 'Premium', 'Electronics', 'Natural Fiber'],
      },
      {
        id: 'bc-006',
        name: 'StarchBlend SB-40',
        slug: 'starchblend-sb40',
        category: 'biodegradable-compounds',
        description: 'Thermoplastic starch blend offering excellent water resistance and biodegradability. Cost-effective solution for single-use applications with strong environmental credentials.',
        shortDescription: 'Cost-effective thermoplastic starch blend for single-use applications.',
        applications: ['Single-use Cutlery', 'Trays', 'Cups', 'Loose Fill Packaging'],
        features: ['Cost Competitive', 'Rapid Biodegradation', 'Starch Based', 'Low Carbon Footprint'],
        specifications: [
          { label: 'Starch Content', value: '40', unit: '%' },
          { label: 'MFI', value: '8-12', unit: 'g/10min' },
          { label: 'Tensile Strength', value: '20-25', unit: 'MPa' },
          { label: 'Water Absorption', value: '<3', unit: '%' },
        ],
        images: ['assets/images/products/starchblend-sb40.jpg'],
        thumbnail: 'assets/images/products/starchblend-sb40-thumb.jpg',
        certifications: ['EN 13432', 'OK Biobased'],
        tags: ['Starch', 'Single-use', 'Cost-effective', 'Biodegradable'],
      },
    ];
  }



  getTeamMembers(): TeamMember[] {
    return [
      {
        id: 'm1',
        name: 'Aditya Verma',
        role: 'Founder & CEO',
        summary: 'Visionary entrepreneur with 20+ years in polymer science. Pioneer of sustainable composites in India, Aditya has led the company from a startup to a recognized industry leader.',
        avatar: 'assets/images/team/ceo.jpg',
        linkedin: '#',
        expertise: ['Business Strategy', 'Polymer Science', 'Sustainability'],
      },
      {
        id: 'm2',
        name: 'Dr. Meera Nair',
        role: 'Chief Technology Officer',
        summary: 'PhD in polymer science from IIT Delhi. Dr. Nair leads R&D innovation, holding 12 patents in sustainable composite formulations.',
        avatar: 'assets/images/team/cto.jpg',
        linkedin: '#',
        expertise: ['R&D', 'Patent Development', 'Material Science'],
      },
      {
        id: 'm3',
        name: 'Vikram Singh',
        role: 'Head of Manufacturing',
        summary: 'With 15 years in industrial production, Vikram ensures our state-of-the-art facility operates at peak efficiency with zero-defect philosophy.',
        avatar: 'assets/images/team/manufacturing.jpg',
        expertise: ['Manufacturing', 'Quality Control', 'Process Optimization'],
      },
      {
        id: 'm4',
        name: 'Ananya Krishnan',
        role: 'Head of Sustainability',
        summary: 'Environmental scientist dedicated to integrating circular economy principles into every product we create. Leads our green certification programs.',
        avatar: 'assets/images/team/sustainability.jpg',
        linkedin: '#',
        expertise: ['Environmental Science', 'Circular Economy', 'Certifications'],
      },
    ];
  }

  getCertifications(): Certification[] {
    return [
      { id: 'c1', name: 'ISO 14001:2015', issuer: 'Bureau Veritas', year: '2019', icon: 'verified_user', description: 'Environmental Management System', badge: 'Environmental'},
      { id: 'c2', name: 'ISO 9001:2015', issuer: 'TÜV SÜD', year: '2018', icon: 'workspace_premium', description: 'Quality Management System', badge: 'Quality' },
      { id: 'c3', name: 'EN 13432', issuer: 'DIN CERTCO', year: '2020', icon: 'eco', description: 'Compostable Packaging Standard', badge: 'Compostable' },
      { id: 'c4', name: 'ASTM D6400', issuer: 'BPI', year: '2020', icon: 'recycling', description: 'Compostable Plastics Standard', badge: 'BPI Certified' },
      { id: 'c5', name: 'OK Compostable', issuer: 'TÜV Austria', year: '2021', icon: 'grass', description: 'Compostable Content Certification', badge: 'Compostable' },
      { id: 'c6', name: 'REACH Compliant', issuer: 'ECHA', year: '2022', icon: 'health_and_safety', description: 'EU Chemical Safety Compliance', badge: 'REACH' },
    ];
  }

  getBlogPosts(): BlogPost[] {
    return [
      {
        id: 'b1',
        slug: 'future-of-biodegradable-plastics-2026',
        title: 'The Future of Compostable Materials: Trends Shaping 2026 and Beyond',
        excerpt: 'As waste challenges rise, compostable materials are emerging as a cornerstone of responsible manufacturing. Explore the trends driving this revolution.',
        content: '',
        coverImage: 'assets/images/blog/biodegradable-future.jpg',
        author: { name: 'Dr. Meera Nair', avatar: 'assets/images/team/cto.jpg', role: 'CTO, Aditya Polymers' },
        category: 'innovation',
        tags: ['Biodegradable', 'Future Trends', 'Sustainability', 'Innovation'],
        publishedAt: '2026-05-20',
        readTime: 8,
        featured: true,
        views: 3240,
      },
      {
        id: 'b2',
        slug: 'natural-fiber-composites-automotive',
        title: 'Natural Fiber Composites Revolutionizing Automotive Manufacturing',
        excerpt: 'How jute, hemp, and kenaf fiber composites are replacing glass fiber in modern vehicles, reducing weight and CO₂ footprint by up to 40%.',
        content: '',
        coverImage: 'assets/images/blog/automotive-composites.jpg',
        author: { name: 'Vikram Singh', avatar: 'assets/images/team/manufacturing.jpg', role: 'Head of Manufacturing' },
        category: 'case-studies',
        tags: ['Automotive', 'Natural Fiber', 'Weight Reduction', 'Case Study'],
        publishedAt: '2026-04-15',
        readTime: 6,
        featured: false,
        views: 1870,
      },
      {
        id: 'b3',
        slug: 'eu-single-use-plastics-directive-impact',
        title: 'Single-Use Waste Rules: What Manufacturers Must Know',
        excerpt: 'A comprehensive breakdown of sustainability requirements, timelines, and how switching to compostable materials ensures full compliance.',
        content: '',
        coverImage: 'assets/images/blog/eu-directive.jpg',
        author: { name: 'Ananya Krishnan', avatar: 'assets/images/team/sustainability.jpg', role: 'Head of Sustainability' },
        category: 'industry-news',
        tags: ['EU Regulation', 'Compliance', 'Single-use Plastics', 'Policy'],
        publishedAt: '2026-03-10',
        readTime: 7,
        featured: false,
        views: 2150,
      },
      {
        id: 'b4',
        slug: 'circular-economy-sustainable-materials',
        title: 'Building a Circular Economy with Sustainable Materials',
        excerpt: 'From cradle-to-cradle design to industrial composting, discover how sustainable materials close the loop and create value from waste.',
        content: '',
        coverImage: 'assets/images/blog/circular-economy.jpg',
        author: { name: 'Ananya Krishnan', avatar: 'assets/images/team/sustainability.jpg', role: 'Head of Sustainability' },
        category: 'sustainability',
        tags: ['Circular Economy', 'Sustainable Materials', 'Zero Waste', 'Composting'],
        publishedAt: '2026-02-28',
        readTime: 5,
        featured: false,
        views: 1340,
      },
      {
        id: 'b5',
        slug: 'pbat-pla-blends-packaging',
        title: 'PBAT/PLA Blends: Crafting the Perfect Compostable Film',
        excerpt: 'Deep dive into the science of blending PBAT and PLA to achieve the optimal balance of flexibility, strength, and compostability for modern packaging.',
        content: '',
        coverImage: 'assets/images/blog/pbat-pla-blends.jpg',
        author: { name: 'Dr. Meera Nair', avatar: 'assets/images/team/cto.jpg', role: 'CTO, Aditya Polymers' },
        category: 'research',
        tags: ['PBAT', 'PLA', 'Film', 'Research', 'Compostable'],
        publishedAt: '2026-01-20',
        readTime: 10,
        featured: false,
        views: 980,
      },
      {
        id: 'b6',
        slug: 'agricultural-biodegradable-mulch-films',
        title: 'Biodegradable Mulch Films: Transforming Indian Agriculture',
        excerpt: 'How compostable mulch films are supporting cleaner agricultural practices while improving crop yields and reducing labor costs.',
        content: '',
        coverImage: 'assets/images/blog/agricultural-films.jpg',
        author: { name: 'Aditya Verma', avatar: 'assets/images/team/ceo.jpg', role: 'CEO, Aditya Polymers' },
        category: 'case-studies',
        tags: ['Agriculture', 'Mulch Film', 'India', 'Case Study'],
        publishedAt: '2025-12-10',
        readTime: 9,
        featured: false,
        views: 2560,
      },
    ];
  }
}
